// ===================== ARCOS 2, 3 Y 4: misiones y escenas =====================
// Mismo formato que misiones.js. Se suma a window.MISIONES y window.ESCENAS.
(function () {
  const M = window.MISIONES, E = window.ESCENAS; if (!M || !E) return;
  const H = (c) => () => (typeof Store !== "undefined" && (Store.world?.history || []).find((h) => h.cap === c)?.id) || "";
  const was = (c, id) => ({ if: () => H(c)() === id });
  const has = (f) => (G) => !!G.g.flags?.[f] || !!(typeof Store !== "undefined" && Store.world?.flags?.[f]);
  const ORD = (n, plus = 0) => ({ n, lvl: "rec", plus, img: "Cultista del Crepúsculo", aff: "Sombra" });
  const A2 = "Año 2", A3 = "Año 2 · Las profundidades", A4 = "Año 3 · Último año";

  // ============================== ARCO 2: La Orden del Crepúsculo
  Object.assign(M, {
    11: { sub: A2 + " · Otoño", steps: [
      { k: "scene", id: "c11_vuelta", t: "Un año más oscuro", auto: true },
      { k: "go", r: "alba", p: 1, t: "Vuelve a Sunrise Academy" },
      { k: "scene", id: "c11_ilvara", t: "La clase de Ilvara", auto: true },
      { k: "choice", t: "Prepárate para el nuevo año" },
      { k: "scene", id: "c11_noticia", t: "Noticias del Templo de Piedra", auto: true },
      { k: "vote", t: "¿Por dónde empieza el grupo?" } ] },
    12: { sub: A2 + " · Otoño", steps: [
      { k: "scene", id: "c12_viaje", t: "Rumbo a las Llanuras", auto: true },
      { k: "go", r: "llan", p: 2, t: "Ve a los Campos de Trigo" },
      { k: "hunt", r: "llan", p: 2, n: 3, t: "Los trigales están llenos de criaturas: vence 3" },
      { k: "go", r: "llan", p: 6, t: "Llega al Templo de Piedra" },
      { k: "scene", id: "c12_templo", t: "El círculo roto", auto: true },
      { k: "choice", t: "Decide qué haces en el templo" },
      { k: "boss", t: "Vence al Cultista que ronda el templo" },
      { k: "vote", t: "Los ladrones se esconden esta noche" } ] },
    13: { sub: A2 + " · Invierno", steps: [
      { k: "scene", id: "c13_carta", t: "Una invitación real", auto: true },
      { k: "go", r: "cap", p: 0, t: "Viaja a la Plaza Real (Capital de Solvaria)" },
      { k: "scene", id: "c13_corte", t: "La corte del Rey", auto: true },
      { k: "choice", t: "Decide cómo pasas la noche en palacio" },
      { k: "fight", r: "cap", p: 0, t: "Un ladrón en los jardines de palacio", e: ORD("Espía encapuchado") },
      { k: "vote", t: "El encargo del rey" } ] },
    14: { sub: A2 + " · Invierno", steps: [
      { k: "scene", id: "c14_pip", t: "El rumor de Pip", auto: true },
      { k: "go", r: "cap", p: 4, t: "Baja a las Alcantarillas" },
      { k: "hunt", r: "cap", p: 4, n: 3, t: "Abrete paso por los túneles: vence 3" },
      { k: "scene", id: "c14_voces", t: "Voces detrás de la reja", auto: true },
      { k: "choice", t: "Decide cómo te acercas" },
      { k: "boss", t: "Vence al Capitán del Crepúsculo" },
      { k: "vote", t: "¿A quién se lo contáis?" } ] },
    15: { sub: A2 + " · Invierno", steps: [
      { k: "scene", id: "c15_festival", t: "El Festival del Sol", auto: true },
      { k: "go", r: "cap", p: 2, t: "Ve al Coliseo Real" },
      { k: "scene", id: "c15_ataque", t: "Las luces se apagan", auto: true },
      { k: "fight", r: "cap", p: 2, t: "La Orden cae desde las gradas", e: ORD("Asaltante del Crepúsculo", 1) },
      { k: "choice", t: "Decide qué haces en el caos" },
      { k: "vote", t: "Solo da tiempo a una cosa" } ] },
    16: { sub: A2 + " · Primavera", steps: [
      { k: "scene", id: "c16_pistas", t: "Todas las pistas llevan al mar", auto: true },
      { k: "go", r: "costa", p: 0, t: "Viaja a Puerto Rayo" },
      { k: "scene", id: "c16_varo", t: "El Capitán Varo «Trueno»", auto: true },
      { k: "hunt", r: "costa", p: 2, n: 2, t: "Demuestra tu valor en el Arrecife Chispeante: vence 2" },
      { k: "choice", t: "Decide cómo tratas con Varo" },
      { k: "vote", t: "¿Qué hace el grupo con los piratas?" } ] },
    17: { sub: A2 + " · Primavera", steps: [
      { k: "scene", id: "c17_tormenta", t: "Llega la tormenta", auto: true },
      { k: "go", r: "costa", p: 5, t: "Llega al Santuario de las Mareas" },
      { k: "scene", id: "c17_brisa", t: "Brisa Sal, empapada", auto: true },
      { k: "choice", t: "Decide cómo salvas la Perla" },
      { k: "boss", t: "Vence a la Sacerdotisa del Crepúsculo" },
      { k: "vote", t: "¿Dónde guardáis la Perla?" } ] },
    18: { sub: A2 + " · Verano", steps: [
      { k: "scene", id: "c18_sospechas", t: "Sospechas en la academia", auto: true },
      { k: "go", r: "alba", p: 1, t: "Vuelve a Sunrise Academy" },
      { k: "choice", t: "Decide cómo investigas" },
      { k: "fight", r: "alba", p: 1, t: "Alguien te sigue por los pasillos", e: ORD("Espía de la torre norte", 1) },
      { k: "scene", id: "c18_iniciales", t: "I. N.", auto: true },
      { k: "vote", t: "¿Qué hacéis con las sospechas?" } ] },
    19: { sub: A2 + " · Verano", steps: [
      { k: "scene", id: "c19_torre", t: "La torre norte", auto: true },
      { k: "scene", id: "c19_te", t: "Una taza de té", auto: true },
      { k: "choice", t: "Decide qué haces con Ilvara" },
      { k: "fight", r: "alba", p: 1, t: "Los guardianes de sombra de Ilvara", e: { n: "Sombra de la Orden", lvl: "rec", plus: 1, img: "Espectros", aff: "Sombra" } },
      { k: "scene", id: "c19_huida", t: "Ilvara escapa", auto: true },
      { k: "vote", t: "¿Qué hace el grupo?" } ] },
    20: { sub: A2 + " · Fin del año", steps: [
      { k: "scene", id: "c20_luna", t: "Luna nueva", auto: true },
      { k: "go", r: "cap", p: 5, t: "Sube a la Torre de las Horas" },
      { k: "fight", r: "cap", p: 5, t: "Los guardianes del reloj", e: ORD("Guardián del Crepúsculo", 1) },
      { k: "scene", id: "c20_circulo", t: "El círculo de reliquias", auto: true },
      { k: "choice", t: "Decide qué haces en la torre" },
      { k: "boss", t: "Vence al Eclipse" },
      { k: "scene", id: "c20_derrota", t: "El Eclipse cae", auto: true },
      { k: "vote", t: "El destino de Ilvara" } ] },

    // ============================== ARCO 3: Lo que hay debajo
    21: { sub: A3, steps: [
      { k: "scene", id: "c21_temblor", t: "Temblores al amanecer", auto: true },
      { k: "go", r: "alba", p: 1, t: "Reúnete en la academia" },
      { k: "scene", id: "c21_nyssa", t: "La diosa que no responde", auto: true },
      { k: "choice", t: "Decide cómo te preparas" },
      { k: "vote", t: "Nyssa ha caído en la sombra" } ] },
    22: { sub: A3, steps: [
      { k: "scene", id: "c22_paramo", t: "El Páramo sin estrellas", auto: true },
      { k: "go", r: "viol", p: 2, t: "Cruza el Bosque Marchito" },
      { k: "hunt", r: "viol", p: 2, n: 2, t: "El bosque está lleno de sombras: vence 2" },
      { k: "go", r: "viol", p: 5, t: "Entra en el Templo del Velo" },
      { k: "scene", id: "c22_velo", t: "El Velo roto", auto: true },
      { k: "choice", t: "Decide qué haces en el templo" },
      { k: "boss", t: "Libera a Nyssa: vence a su avatar corrupto" },
      { k: "scene", id: "c22_nyssa", t: "Nyssa despierta", auto: true },
      { k: "vote", t: "Decisión del grupo" } ] },
    23: { sub: A3, steps: [
      { k: "scene", id: "c23_choza", t: "Una choza que cambia de sitio", auto: true },
      { k: "go", r: "viol", p: 1, t: "Encuentra la Choza de Morwen" },
      { k: "scene", id: "c23_morwen", t: "La bruja del Páramo", auto: true },
      { k: "choice", t: "Decide cómo pagas a Morwen" },
      { k: "fight", r: "viol", p: 1, t: "Algo sale del caldero", e: { n: "Semilla de sombra", lvl: "rec", img: "Criaturas sin forma", aff: "Sombra" } },
      { k: "vote", t: "El trato de Morwen" } ] },
    24: { sub: A3, steps: [
      { k: "scene", id: "c24_nieve", t: "Nieve que cae hacia arriba", auto: true },
      { k: "go", r: "esc", p: 0, t: "Llega al Monasterio Nube Blanca" },
      { k: "scene", id: "c24_kiri", t: "La Hermana Kiri", auto: true },
      { k: "go", r: "esc", p: 6, t: "Sube hasta El Ancla" },
      { k: "choice", t: "Decide cómo detienes la cadena" },
      { k: "boss", t: "Vence al avatar corrupto de Orvath" },
      { k: "vote", t: "La cadena de Orvath" } ] },
    25: { sub: A3, steps: [
      { k: "scene", id: "c25_forja", t: "El fuego se apaga", auto: true },
      { k: "go", r: "quem", p: 0, t: "Viaja a Forjaroja" },
      { k: "scene", id: "c25_ignara", t: "La rabia de Ignara", auto: true },
      { k: "hunt", r: "quem", p: 1, n: 2, t: "Busca cultistas en las Minas de Rubí: vence 2" },
      { k: "go", r: "quem", p: 5, t: "Entra en el Templo de la Forja" },
      { k: "choice", t: "Decide cómo ayudas a Ignar" },
      { k: "boss", t: "Vence al avatar corrupto de Ignar" },
      { k: "vote", t: "¿Os quedáis a defender Forjaroja?" } ] },
    26: { sub: A3, steps: [
      { k: "scene", id: "c26_lago", t: "El lago que miente", auto: true },
      { k: "go", r: "verde", p: 1, t: "Vuelve al Lago Espejo" },
      { k: "scene", id: "c26_reflejo", t: "Tu reflejo", auto: true },
      { k: "choice", t: "Decide qué haces frente al lago" },
      { k: "boss", t: "Vence al avatar corrupto de Mirael" },
      { k: "vote", t: "El camino que muestra el lago" } ] },
    27: { sub: A3, steps: [
      { k: "scene", id: "c27_sotano", t: "El sótano de Tobble", auto: true },
      { k: "go", r: "alba", p: 1, t: "Vuelve a la academia" },
      { k: "scene", id: "c27_maquina", t: "La máquina", auto: true },
      { k: "choice", t: "Decide cómo ayudas" },
      { k: "fight", r: "alba", p: 1, t: "Un espía intenta sabotear la máquina", e: ORD("Saboteador del Crepúsculo") },
      { k: "vote", t: "¿Para qué usaréis la máquina?" } ] },
    28: { sub: A3, steps: [
      { k: "scene", id: "c28_ejercito", t: "Un ejército en marcha", auto: true },
      { k: "go", r: "quem", p: 2, t: "Llega al Mar de Ceniza" },
      { k: "scene", id: "c28_thorne", t: "Thorne los ha visto", auto: true },
      { k: "hunt", r: "quem", p: 2, n: 3, t: "Frena a la vanguardia: vence 3" },
      { k: "choice", t: "Decide qué haces en la batalla" },
      { k: "fight", r: "quem", p: 2, t: "El comandante de la marcha", e: ORD("Comandante del Crepúsculo", 2) },
      { k: "vote", t: "El ejército se retira" } ] },
    29: { sub: A3, steps: [
      { k: "scene", id: "c29_grieta", t: "La escalera hacia abajo", auto: true },
      { k: "go", r: "viol", p: 4, t: "Baja a La Entrada de Abajo" },
      { k: "scene", id: "c29_susurros", t: "Cada escalón susurra tu nombre", auto: true },
      { k: "choice", t: "Decide cómo bajas" },
      { k: "boss", t: "Vence al Heraldo de Vaelmor" },
      { k: "vote", t: "Delante de la puerta de la tumba" } ] },
    30: { sub: A3 + " · Fin del año", steps: [
      { k: "scene", id: "c30_tumba", t: "Dentro de la tumba", auto: true },
      { k: "scene", id: "c30_voz", t: "La voz de Vaelmor", auto: true },
      { k: "choice", t: "Decide qué haces ante Vaelmor" },
      { k: "boss", t: "Vence a Vaelmor, medio despierto" },
      { k: "scene", id: "c30_debil", t: "Vaelmor se tambalea", auto: true },
      { k: "vote", t: "La decisión más importante hasta ahora" } ] },

    // ============================== ARCO 4: La verdad de la Cumbre
    31: { sub: A4 + " · Otoño", steps: [
      { k: "scene", id: "c31_velas", t: "Velas a mediodía", auto: true },
      { k: "go", r: "alba", p: 1, t: "Vuelve a Sunrise Academy" },
      { k: "scene", id: "c31_seraphina", t: "La visión de Seraphina", auto: true },
      { k: "choice", t: "Decide cómo empiezas el último año" },
      { k: "vote", t: "¿Por dónde empezáis a buscar la verdad?" } ] },
    32: { sub: A4 + " · Otoño", steps: [
      { k: "scene", id: "c32_luces", t: "Luces en el faro", auto: true },
      { k: "go", r: "alba", p: 3, t: "Ve al Faro Antiguo" },
      { k: "fight", r: "alba", p: 3, t: "Ecos desesperados", e: { n: "Ecos de luz", lvl: "rec", img: "Ecos del pasado", aff: "Luz" } },
      { k: "scene", id: "c32_ganadores", t: "Los que no volvieron", auto: true },
      { k: "choice", t: "Decide qué haces entre los ecos" },
      { k: "vote", t: "¿Se lo contáis a Kael?" } ] },
    33: { sub: A4 + " · Invierno", steps: [
      { k: "scene", id: "c33_kael", t: "Un padre", auto: true },
      { k: "go", r: "alba", p: 4, t: "Baja a la Cueva del Primer Rayo" },
      { k: "hunt", r: "alba", p: 4, n: 2, t: "La cueva está llena de luz rota: vence 2" },
      { k: "choice", t: "Decide qué haces con el eco" },
      { k: "boss", t: "Enfréntate al Eco del Campeón" },
      { k: "scene", id: "c33_nombre", t: "Un nombre recordado", auto: true },
      { k: "vote", t: "¿Liberáis al hijo de Kael?" } ] },
    34: { sub: A4 + " · Invierno", steps: [
      { k: "scene", id: "c34_mascara", t: "Sin máscara", auto: true },
      { k: "go", r: "viol", p: 3, t: "Ve al Salón de Baile Hundido" },
      { k: "fight", r: "viol", p: 3, t: "Los fantasmas del salón", e: { n: "Bailarines sombríos", lvl: "rec", aff: "Sombra" } },
      { k: "scene", id: "c34_baile", t: "El baile hundido", auto: true },
      { k: "choice", t: "Decide qué haces con Nyx" },
      { k: "vote", t: "¿Acompañáis a Nyx esta noche?" } ] },
    35: { sub: A4 + " · Primavera", steps: [
      { k: "scene", id: "c35_llamada", t: "Una audiencia de noche", auto: true },
      { k: "go", r: "cap", p: 0, t: "Viaja a la Plaza Real" },
      { k: "scene", id: "c35_rey", t: "La corona y la luz", auto: true },
      { k: "choice", t: "Decide qué haces con la verdad del rey" },
      { k: "vote", t: "¿Qué hacéis con lo que sabéis?" } ] },
    36: { sub: A4 + " · Verano", steps: [
      { k: "scene", id: "c36_prueba", t: "La última Prueba", auto: true },
      { k: "go", r: "alba", p: 1, t: "Vuelve a la academia para la Prueba" },
      { k: "fight", r: "alba", p: 1, t: "El combate de la Prueba: Darius", any: true, e: { n: "Darius Valcor", lvl: "rec", rival: true } },
      { k: "choice", t: "Supera las pruebas" },
      { k: "scene", id: "c36_ganadores", t: "Ganadores", auto: true },
      { k: "vote", t: "¿Quién sube la escalera?" } ] },
    37: { sub: A4 + " · Verano", steps: [
      { k: "scene", id: "c37_mapa", t: "El mapa de Brisa", auto: true },
      { k: "go", r: "costa", p: 0, t: "Busca a Varo en Puerto Rayo para zarpar" },
      { k: "scene", id: "c37_zarpar", t: "Rumbo a las Islas Perdidas", auto: true },
      { k: "go", r: "lost", p: 0, t: "Llega a la Isla del Umbral" },
      { k: "choice", t: "Decide qué haces ante la Puerta" },
      { k: "boss", t: "Vence al Guardián del Umbral" },
      { k: "vote", t: "El fragmento de Solen" } ] },
    38: { sub: A4 + " · Verano", steps: [
      { k: "scene", id: "c38_hilos", t: "Hilos de luz", auto: true },
      { k: "go", r: "lost", p: 4, t: "Llega al Telar de Norna" },
      { k: "scene", id: "c38_norna", t: "Norna, la Hilandera", auto: true },
      { k: "choice", t: "Decide qué haces en el Telar" },
      { k: "vote", t: "¿Queréis saber qué hilo se vuelve sol?" } ] },
    39: { sub: A4 + " · Fin", steps: [
      { k: "scene", id: "c39_escalera", t: "La escalera se abre", auto: true },
      { k: "go", r: "alba", p: 6, t: "Sube a la Cumbre del Alba" },
      { k: "scene", id: "c39_deseos", t: "Noventa y siete deseos", auto: true },
      { k: "choice", t: "Decide cómo subes" },
      { k: "boss", t: "Vence al Guardián de la Cumbre" },
      { k: "vote", t: "Ante el Guardián" } ] },
    40: { sub: A4 + " · Fin", steps: [
      { k: "scene", id: "c40_solen", t: "Solen", auto: true },
      { k: "choice", t: "Decide qué haces en la Cumbre" },
      { k: "boss", t: "Vence al eco de todos los deseos" },
      { k: "scene", id: "c40_decision", t: "El momento de decidir", auto: true },
      { k: "vote", t: "El final del sol" } ] },
  });

  Object.assign(E, {
    // ================================================= ARCO 2
    c11_vuelta: { bg: "patio", lines: [
      "Empieza el segundo año. El sol sale tarde y se pone temprano; en el patio ya nadie bromea con eso.",
      was(10, "verdad") && { if: () => H(10)() === "verdad", then: ["El verano pasado, el grupo juró descubrir la verdad de la Cumbre. Este año empieza la búsqueda."] },
      { if: () => H(10)() === "orden", then: ["El verano pasado, el grupo juró destruir a la Orden del Crepúsculo. Este año, la Orden está más cerca que nunca."] },
      { if: () => H(10)() === "subir", then: ["El verano pasado, el grupo juró llegar a la Cumbre. Pero desde que Maelis no volvió, esa promesa pesa más."] },
      ["thorne", "¡{n}! Pensé que no volvías. Este verano he entrenado tanto que ya no me caben las camisas."],
      ["pip", "Novedades del verano: tres parejas rotas, dos compromisos y un fantasma nuevo en el baño del ala este. De nada."],
      "Entre los estudiantes nuevos hay una figura con una máscara blanca, sin rostro. Nadie sabe su nombre. Se sienta sola, al fondo.",
      ["pip", "Ese es «El Enmascarado». Se ha apuntado a la Escalera sin decir su nombre. Ni yo sé quién es. Y eso me duele profesionalmente."],
      "Vuelve a la academia. Las clases empiezan hoy.",
    ].filter(Boolean) },
    c11_ilvara: { bg: "observatorio", lines: [
      ["ilvara", "Sentaos. Hoy no hay magia. Hoy hay números."],
      "La profesora Ilvara proyecta en la pared una curva que baja, baja y baja. Cada pocos años, cae de golpe.",
      ["ilvara", "Esto es el sol. Cada escalón es una Prueba de la Cumbre. Cada deseo concedido."],
      { if: has("pista_ocaso"), then: ["Recuerdas los cristales del acantilado, el primer examen. Brillaban menos que en los libros. Lo sabías desde hace un año."] },
      ["seraphina", "Si eso es verdad… ¿por qué el rey sigue pagando la Prueba cada año?"],
      ["ilvara", "Excelente pregunta, señorita Lux. Guárdela. Algún día le hará falta."],
      "Mientras recoges tus cosas, Ilvara te mira un segundo de más. Como si midiera algo también en ti.",
    ] },
    c11_noticia: { bg: "patio", lines: [
      "Esa tarde, un mensajero entra en el patio a caballo, cubierto de polvo.",
      ["aurelia", "La Orden del Crepúsculo ha asaltado el Templo de Piedra, en las Llanuras. Se han llevado la reliquia de Grudhal."],
      ["aurelia", "Los campesinos dicen que el trigo tiembla por las noches, como si la tierra tuviera miedo."],
      ["thorne", "La Orden otra vez. Esta vez no se nos escapan."],
      ["aurelia", "No os pido que vayáis. Pero sé que iréis de todas formas. Así que al menos id juntos."],
      "El grupo tiene que decidir por dónde empezar.",
    ] },
    c12_viaje: { bg: "llan", lines: [
      { if: () => H(11)() === "templo", then: ["El grupo decidió seguir el rastro de la reliquia. El camino lleva a las Llanuras Doradas."] },
      { if: () => H(11)() === "capital", then: ["La Capital prometió ayuda… y envió dos guardias con sueño. Al final, el camino lleva igualmente a las Llanuras."] },
      { if: () => H(11)() === "puerto", then: ["En Puerto Rayo nadie quiso hablar, pero un marinero borracho mencionó «el templo del trigo». Rumbo a las Llanuras."] },
      "El viento de las Llanuras Doradas huele a pan y a humo. Los trigales, altos como un hombre, se mueven sin viento.",
      ["garrok", "No me gusta. El trigo no debería moverse así."],
      "Algo se esconde entre las espigas. Tendrás que abrirte paso hasta el templo.",
    ] },
    c12_templo: { bg: "llan", lines: [
      "El círculo de piedras del Templo de Grudhal está roto. En el centro, donde estaba la reliquia, solo queda un hueco lleno de ceniza negra.",
      "Un anciano campesino se acerca con el sombrero entre las manos.",
      "«Grudhal sostenía la tierra. Desde que se la llevaron, las raíces se sueltan solas. Si esto sigue así, no habrá cosecha.»",
      ["thorne", "(olfateando) Uno de ellos sigue aquí. Lo huelo. Ceniza y miedo."],
      "Una figura encapuchada se esconde entre las piedras rotas, esperando la noche.",
    ] },
    c13_carta: { bg: "patio", lines: [
      "Una carta con el sello del sol dorado llega a la academia. La lee la directora, en voz alta, delante de todos.",
      ["aurelia", "«Su Majestad Aldric III invita a los mejores estudiantes de Sunrise a proteger el Festival del Sol en la Capital.»"],
      ["casimir", "¡Por fin algo elegante en este curso! Os quiero con los zapatos limpios y la lengua quieta."],
      ["darius", "Mi familia estará allí. Mi padre. Genial."],
      "Viaja a la Plaza Real, en la Capital de Solvaria.",
    ] },
    c13_corte: { bg: "salon", lines: [
      "El palacio brilla con miles de velas. Demasiadas velas, para un mundo que se apaga.",
      ["aldric", "Así que estos son los alumnos de Aurelia. Jóvenes. Bien. Los jóvenes todavía creen que el mundo se puede salvar."],
      ["aldric", "El Festival del Sol recuerda a Solvaria que el sol nos cuida. Que la Orden lo sabotee sería… inconveniente."],
      ["lysa", "(en voz baja, a tu lado) El rey habla de «inconveniente». Yo hablo de gente muerta. Ojos abiertos esta noche."],
      { c: [
        { l: "«Estaremos atentos, capitana.»", fx: { vinc: { "Capitana Lysa": 1 } }, then: [["lysa", "Bien. Por fin alguien que no viene solo a comer."]] },
        { l: "Observas al rey un rato largo.", then: ["El rey sonríe a todos. Pero cuando cree que nadie lo mira, se frota los ojos como alguien que no duerme desde hace años."] },
      ] },
    ] },
    c14_pip: { bg: "taberna", lines: [
      ["pip", "Tengo un rumor. Caro. Muy caro. Para vosotros… gratis. No me miréis así, me estoy volviendo buena persona."],
      ["pip", "La Orden se reúne bajo la Plaza Real. En las alcantarillas. Detrás de una reja oxidada."],
      ["pip", "Y una de las voces… habla como una profesora. No sé cuál. Eso es lo que me da miedo."],
      "Baja a las Alcantarillas de la Capital.",
    ] },
    c14_voces: { bg: "cueva", lines: [
      "Detrás de la reja oxidada, a la luz de una sola vela, varias figuras encapuchadas rodean un mapa.",
      "«…las mediciones son claras. Le quedan quizá diez deseos al sol. Quizá menos.»",
      "La voz es tranquila, precisa, femenina. Te suena. No sabes de qué.",
      "«El Festival nos dará el Reloj de Kronea. Con tres reliquias, el círculo estará completo.»",
      "Un guardia grande, con armadura negra, se gira hacia la reja. Os ha oído.",
    ] },
    c15_festival: { bg: "arena", lines: [
      { if: () => H(14)() === "aurelia", then: ["Aurelia envió avisos a la guardia. Hay más soldados que nunca en las gradas."] },
      { if: () => H(14)() === "secreto", then: ["Nadie más sabe lo que oísteis. Si pasa algo esta noche, estaréis solos."] },
      "El Coliseo Real está lleno hasta la última grada. Banderas doradas, niños con coronas de papel, olor a pan de miel.",
      ["aldric", "¡Pueblo de Solvaria! ¡Mientras el sol nos cuide, nada nos faltará!"],
      "Ve al Coliseo Real. El rey está a punto de alzar la antorcha del sol.",
    ] },
    c15_ataque: { bg: "arena", lines: [
      "El rey alza la antorcha. Y todas las luces del coliseo se apagan a la vez.",
      { sfx: "boss" },
      "Desde lo alto de las gradas caen figuras encapuchadas. Humo morado. Gritos. Una tormenta mágica se forma sobre la arena.",
      "Entre el humo ves a alguien que corre hacia la Torre de las Horas con un reloj dorado bajo el brazo: el Reloj de Kronea.",
      ["lysa", "¡Guardias, al rey! ¡Estudiantes, donde podáis!"],
    ] },
    c16_pistas: { bg: "puerto", lines: [
      "Todas las pistas llevan al mar. Barcos que salen de noche, sin luces, con gente encapuchada a bordo.",
      ["brisa", "Esos barcos son del Capitán Varo «Trueno». Es un pirata. Un buen pirata, si eso existe."],
      ["brisa", "No es de la Orden. Pero le pagan. Y a Varo le gusta que le paguen."],
      "Viaja a Puerto Rayo, en la Costa Tormenta.",
    ] },
    c16_varo: { bg: "puerto", lines: [
      "Puerto Rayo huele a pescado, a tormenta y a ron. En el muelle más grande, un dracónido azul cuenta monedas sobre un barril.",
      ["varo", "¡Estudiantes de Sunrise! ¿Venís a arrestarme o a comprarme un barco? Los dos son caros."],
      ["varo", "Sí, llevo gente encapuchada al Santuario de las Mareas. Pagan en oro limpio y no vomitan en la cubierta. Clientes ideales."],
      ["varo", "¿Queréis que os ayude? Demostrad que no sois niños de academia. En el Arrecife hay bichos que asustan a mis marineros."],
    ] },
    c17_tormenta: { bg: "puerto", lines: [
      { if: () => H(16)() === "aliarse", then: ["Varo cumple su parte: os lleva en su barco hasta el Santuario, en plena noche, con la tormenta encima."] },
      { if: () => H(16)() === "denunciar", then: ["Los piratas están encerrados, pero nadie más sabe navegar esta tormenta. Llegaréis por la costa, a pie."] },
      "El cielo se rompe en rayos. El mar se retira de la playa, como si alguien tirara de él desde lejos.",
      "Llega al Santuario de las Mareas antes de que sea tarde.",
    ] },
    c17_brisa: { bg: "puerto", lines: [
      "En el Santuario, la Orden rodea el altar. En su centro brilla una perla del tamaño de un puño: la Perla de Marenna.",
      "Brisa Sal aparece corriendo por la arena, empapada, con el pelo lleno de algas.",
      ["brisa", "¡Si se llevan la Perla, el mar se volverá loco! ¡Mareas de diez metros, puertos hundidos!"],
      ["brisa", "¡Ayudadme a sostener la marea! ¡O a quitarles la Perla! ¡O las dos cosas! ¡Rápido!"],
      "Una sacerdotisa de la Orden levanta los brazos. El agua se alza detrás de ella como un muro.",
    ] },
    c18_sospechas: { bg: "patio", lines: [
      "De vuelta en la academia, medio curso habla de lo mismo: hay un profesor de la Orden. Tiene que haberlo.",
      ["pip", "Mis apuestas: Casimir, tres a uno. Tobble, diez a uno. Brisa, veinte a uno. La directora, cien a uno."],
      ["casimir", "Sé lo que dicen de mí. El Ocaso me hace más fuerte, sí. Soy vampiro. Me hace más fuerte hasta un día nublado."],
      "Pero algunas cosas no encajan. Un sello con las iniciales I. N. Magia de academia. Una voz tranquila que habla de mediciones.",
      "Vuelve a la academia e investiga.",
    ] },
    c18_iniciales: { bg: "observatorio", lines: [
      "El espía cae. En su bolsillo hay una carta sin firmar, escrita con una letra fina, precisa, inclinada a la derecha.",
      { if: has("prueba_letra"), then: ["Es la misma letra de las notas que Ilvara escribe en la pizarra. Exactamente la misma."] },
      { if: has("vio_ilvara"), then: ["Anoche, desde la torre norte, viste una silueta con capa de estrellas mirando el cielo. Tenía orejas de elfa."] },
      "«Todo está listo. La luna nueva será la noche. — I. N.»",
      ["seraphina", "I. N. … No. No puede ser."],
      "Nadie dice el nombre en voz alta. Pero todos lo estáis pensando.",
    ] },
    c19_torre: { bg: "patio", lines: [
      { if: () => H(18)() === "casimir", then: ["Acusasteis a Lord Casimir delante de todos. Él solo sonrió y dijo: «Mirad más arriba». Esa noche, alguien deja una nota en tu puerta: «Torre norte. Medianoche.»"] },
      { if: () => H(18)() === "esperar", then: ["Seguisteis investigando en silencio. Esa noche, alguien deja una nota en tu puerta con la letra de las cartas: «Torre norte. Medianoche. Venid todos.»"] },
      "Subís la escalera de caracol de la torre norte. Arriba hay luz de velas… y olor a té.",
    ] },
    c19_te: { bg: "observatorio", lines: [
      "Ilvara Nocturna os espera sentada, con una taza de té, como si os hubiera invitado a merendar.",
      ["ilvara", "Pasad. Sentaos. No muerdo. Eso lo dejo para Casimir."],
      ["ilvara", "Sí, soy el Eclipse. Imaginaba que tardaríais menos, la verdad."],
      ["ilvara", "He medido el sol durante treinta años. Va a morir. Da igual lo que hagáis. Cada deseo en la Cumbre lo acelera, y el rey no va a dejar de pagar deseos."],
      ["ilvara", "Cuando muera, Vaelmor ocupará su lugar. Eso tampoco lo podéis evitar. Yo solo quiero que ocurra con orden. Sin pánico. Sin guerras."],
      ["ilvara", "La Orden no quiere oscuridad por maldad. La quiere porque es lo único que queda. ¿No lo entendéis?"],
      { c: [
        { l: "«Tiene que haber otra forma.»", then: [["ilvara", "Eso dicen todos los jóvenes. Yo también lo decía. Hace treinta años."]] },
        { l: "«Usted nos enseñó a no rendirnos.»", then: [["ilvara", "…Os enseñé a medir. No es lo mismo."], "Por un segundo, su mano tiembla sobre la taza."] },
      ] },
    ] },
    c19_huida: { bg: "observatorio", lines: [
      "Ilvara se levanta. La sombra de la sala se abre como una cortina.",
      ["ilvara", "Buenas noches. La próxima vez que nos veamos, será en la Torre de las Horas. No lleguéis tarde."],
      "Y desaparece en la oscuridad, con sus cuadernos bajo el brazo.",
      ["kael", "(llegando sin aliento) ¡¿Qué ha pasado aquí?! ¿Dónde está Ilvara?"],
    ] },
    c20_luna: { bg: "patio", lines: [
      { if: () => H(19)() === "aurelia", then: [["aurelia", "Ilvara… mi amiga desde hace treinta años. Y yo sin ver nada. Id. Traedla de vuelta, si podéis."]] },
      { if: () => H(19)() === "perseguir", then: ["Llevais días persiguiendo a Ilvara. Todas las pistas llevan al mismo sitio: la Torre de las Horas."] },
      { if: () => H(19)() === "convencer", then: ["Habéis buscado la forma de convencerla. Quizá haya una. Quizá solo tengáis una oportunidad."] },
      "Luna nueva. En la Capital no brilla ni una estrella. En lo alto de la Torre de las Horas, una luz morada late como un corazón.",
      "Sube a la Torre de las Horas.",
    ] },
    c20_circulo: { bg: "cumbre", lines: [
      "En la cima de la torre, Ilvara ha colocado las reliquias robadas en un círculo de sombra. El gran reloj de la torre marca horas hacia atrás.",
      ["ilvara", "Llegáis a tiempo. Qué puntuales. Mis alumnos favoritos."],
      "Muy lejos, bajo el Páramo Violeta, algo enorme se da la vuelta en su sueño. La torre entera tiembla.",
      ["ilvara", "¿Lo sentís? Ya se está despertando. Solo quiero que despierte con alguien a su lado que lo guíe. ¡Apartaos!"],
    ] },
    c20_derrota: { bg: "cumbre", lines: [
      "Ilvara cae de rodillas. El círculo de sombra se apaga. El reloj vuelve a marcar las horas hacia delante.",
      { if: has("ilvara_escucha"), then: [["ilvara", "…Os he escuchado. Quizá tengáis razón. Quizá haya otra forma. Nunca quise tener razón en esto."]] },
      ["ilvara", "Habéis ganado esta noche. Pero el sol sigue muriendo. Y lo que hay debajo… ya está despierto."],
      "Es el final del segundo año. El grupo tiene que decidir qué hacer con Ilvara Nocturna.",
    ] },

    // ================================================= ARCO 3
    c21_temblor: { bg: "patio", lines: [
      { if: () => H(20)() === "prision", then: ["Ilvara está en una celda de la Capital. Antes de que se la llevaran, dijo: «Os lo dije. Ya ha empezado»."] },
      { if: () => H(20)() === "aliada", then: [["ilvara", "Vaelmor se alimenta de los dioses que guardan su tumba. Nyssa es la primera. Luego vendrá Orvath."], "Ilvara, sin capa de estrellas, parece más vieja. Pero ahora trabaja con vosotros."] },
      { if: () => H(20)() === "huye", then: ["Nadie sabe dónde está Ilvara. Pero alguien ha dejado en tu cuarto un mapa del Páramo con una cruz sobre el Templo del Velo."] },
      "Desde la noche de la Torre de las Horas, la tierra tiembla cada amanecer. Los vasos se caen de las mesas. Los niños lloran sin saber por qué.",
      "Reúnete con los demás en la academia.",
    ] },
    c21_nyssa: { bg: "patio", lines: [
      ["aurelia", "Esta mañana, los devotos de Nyssa han despertado gritando. Su diosa ya no les responde."],
      ["aurelia", "Hace mucho tiempo, los dioses mayores enterraron a Vaelmor bajo el Páramo Violeta. Nyssa y Orvath guardan su tumba."],
      ["aurelia", "Si algo ha envuelto a Nyssa… es él. Desde abajo."],
      ["yara", "(muy pálida) Perdonad… me siento un poco débil. No es nada. Seguid, seguid."],
      ["nyx", "(desde el fondo, con la máscara puesta) El Páramo es mi hogar. Os guiaré, si vais."],
    ] },
    c22_paramo: { bg: "viol", lines: [
      "El Páramo Violeta ya no tiene estrellas. El cielo es un techo negro y liso, como la tapa de una caja.",
      ["nyx", "Antes aquí se veían mil estrellas. Nyssa las encendía cada noche. Ahora mirad."],
      "El Bosque Marchito cruje a tu alrededor. Las sombras se mueven entre los árboles muertos.",
    ] },
    c22_velo: { bg: "viol", lines: [
      "Dentro del Templo del Velo la noche es total. Solo se ven los ojos de los cultistas, brillando.",
      "En el centro, una sombra con forma de mujer flota sobre el altar. Tiene los ojos llenos de algo que no es suyo.",
      ["nyssa", "…¿quién… viene…? No… no os acerquéis… él… está… dentro…"],
      ["nyx", "Es Nyssa. La diosa de mi pueblo. Tenemos que sacarla de ahí."],
    ] },
    c22_nyssa: { bg: "viol", lines: [
      "La sombra se rompe como un cristal. Debajo, una mujer alta, con un velo de estrellas y una luna en la frente, cae de rodillas.",
      ["nyssa", "Me he visto desde dentro… comiéndome mis propias estrellas. Gracias, pequeños."],
      ["nyssa", "Escuchadme: Vaelmor se alimenta de nosotros. Orvath es el siguiente. Después, los que queden."],
      "Una a una, las estrellas vuelven a encenderse sobre el Páramo. Nyx llora en silencio detrás de su máscara.",
    ] },
    c23_choza: { bg: "viol", lines: [
      ["nyx", "Hay alguien en el Páramo que sabe más de Vaelmor que nadie: la bruja Morwen."],
      ["nyx", "Su choza cambia de sitio cada noche. Pero siempre deja un rastro de humo verde. Síguelo."],
      "Busca la Choza de Morwen.",
    ] },
    c23_morwen: { bg: "cueva", lines: [
      "La choza de Morwen huele a hierbas quemadas y a secretos. Un caldero burbujea en el centro, verde y espeso.",
      ["morwen", "Te esperaba. Bueno, esperaba a alguien. Tú servirás."],
      { if: has("semillas"), then: [["morwen", "Ah, traes semillas de sombra. Qué regalo tan feo. Dame, dame."]] },
      ["morwen", "Las semillas de sombra son trocitos de Vaelmor. Cada dios que se traga una, lo acerca un poco más a la superficie."],
      ["morwen", "Sé cómo limpiarlas. Sé cómo esconderos de sus ojos. Pero todo tiene un precio, pequeño. Todo."],
    ] },
    c24_nieve: { bg: "esc", lines: [
      { if: () => H(23)() === "aceptar", then: ["Llevas el amuleto de Morwen colgado al cuello. Pesa más de lo que debería. Algún día te pedirá su favor."] },
      "En los Picos Escarcha, la nieve cae hacia arriba. Las piedras flotan a la altura de la cabeza.",
      "Llega al Monasterio Nube Blanca antes de que la montaña se desarme.",
    ] },
    c24_kiri: { bg: "observatorio", lines: [
      ["kiri", "Llegáis tarde. La gran cadena de Orvath se ha soltado de la montaña esta madrugada."],
      ["kiri", "El avatar del Ancla, cubierto de semillas negras, la arrastra hacia el Páramo. Si llega, la tumba de Vaelmor se abrirá un poco más."],
      ["kiri", "Mis monjes pueden ayudaros a sujetarla. Pero solo un rato. Id. Respirad hondo. Y no miréis abajo."],
      "Sube hasta El Ancla.",
    ] },
    c25_forja: { bg: "quem", lines: [
      "Por primera vez en mil años, el humo de Forjaroja no se ve desde el horizonte. El fuego de la ciudad se ha apagado.",
      ["ignara", "(en una carta urgente) Mi fuego viene de Ignar. Si Ignar cae, Forjaroja cae con él. Venid. Por favor."],
      "Viaja a Forjaroja, en las Tierras Quemadas.",
    ] },
    c25_ignara: { bg: "taberna", lines: [
      "La forja de Ignara está fría. Ella golpea el yunque apagado con el martillo, una y otra vez, con rabia.",
      ["ignara", "¡Mil años! ¡Mil años de fuego! ¡Y unos encapuchados lo apagan con semillitas negras!"],
      ["ignara", "Los cultistas se esconden en las Minas de Rubí. Sacadlos de ahí. Luego iremos juntos al templo."],
    ] },
    c26_lago: { bg: "copaalta", lines: [
      ["sylwen", "Habéis vuelto. Y justo a tiempo. El Lago Espejo ya no refleja lo que hay. Refleja lo que temes."],
      ["sylwen", "Mirael, la diosa de la realidad, está atrapada en su propio reflejo. Mis elfos no se atreven a acercarse."],
      "Vuelve al Lago Espejo.",
    ] },
    c26_reflejo: { bg: "verde", lines: [
      "Te asomas al agua. Tu reflejo no te imita. Te mira.",
      "En el lago ves a tus amigos dándote la espalda, uno a uno. Ves la academia a oscuras. Te ves a ti, solo, en la Cumbre.",
      ["mirael", "Esto es real. Esto es lo que pasará. ¿No lo ves? Ríndete ahora y te ahorrarás el dolor."],
      { c: [
        { l: "«No es real. Es lo que temo, no lo que pasará.»", fx: { rayos: { corazon: 10 } }, then: ["Tu reflejo parpadea. Por un segundo, deja de sonreír."] },
        { l: "Apartas la vista del agua.", then: ["Cuando vuelves a mirar, el reflejo sigue ahí. Esperando."] },
      ] },
    ] },
    c27_sotano: { bg: "patio", lines: [
      ["tobble", "Vosotros. Venid. No, no ha explotado nada. Todavía. Venid al sótano. Tengo algo que enseñaros."],
      ["tobble", "Llevo diez años construyéndolo en secreto. Nadie lo sabe. Bueno, la directora sospecha. Y Pip, claro."],
    ] },
    c27_maquina: { bg: "cueva", lines: [
      "En el sótano de la academia hay una máquina del tamaño de una casa, llena de engranajes de oro, cristales y tubos que brillan.",
      ["tobble", "No la construí para robar luz. La construí para guardarla. Para cuando el sol se apague."],
      ["tobble", "Pero si le pongo las reliquias de los dioses… podría encerrar a Vaelmor en su propia oscuridad. O darle luz a Solen."],
      { if: has("reliquia_grudhal"), then: ["La reliquia de Grudhal ya está en el sótano, esperando."] },
      { if: has("reliquia_kronea"), then: ["El Reloj de Kronea marca los segundos en una estantería."] },
      { if: has("reliquia_marenna"), then: ["La Perla de Marenna brilla dentro de una jarra de agua salada."] },
      ["tobble", "Solo sirve para una cosa. Una vez. Tendréis que elegir."],
    ] },
    c28_ejercito: { bg: "quem", lines: [
      "Desde lo alto de una duna negra lo veis: el ejército de la Orden marcha por el Mar de Ceniza hacia el Páramo.",
      "Son cientos. Llevan carros cubiertos de lonas negras, llenos de semillas de sombra.",
      "Llega al Mar de Ceniza.",
    ] },
    c28_thorne: { bg: "quem", lines: [
      ["thorne", "…Son ellos. Los de las capas rojas. Los que quemaron mi manada."],
      "Thorne aprieta los puños hasta que le sangran. Sus ojos brillan amarillos.",
      { if: (G) => !!G.g.flags?.romance_thorne || (G.vinculos || []).some((v) => v.nombre === "Thorne Colmillo" && v.valor >= 3), then: [["thorne", "No me dejes hacer una locura. Tú no. Por favor."]] },
      "La vanguardia os ha visto. Vienen hacia vosotros.",
    ] },
    c29_grieta: { bg: "viol", lines: [
      { if: () => H(28)() === "reunir", then: ["Habéis reunido aliados: monjes de Kiri, herreros de Ignara, piratas de Varo. Os esperan en el borde del Páramo."] },
      { if: () => H(28)() === "perseguir", then: ["Habéis perseguido al ejército sin descanso. Estáis agotados, pero la Orden también."] },
      "La grieta del Páramo se ha convertido en una escalera que baja hacia la oscuridad. No se ve el fondo.",
      "Baja a La Entrada de Abajo.",
    ] },
    c29_susurros: { bg: "cueva", lines: [
      "Cada escalón susurra tu nombre. Con tu voz. Con la voz de tu madre. Con la voz de tus amigos.",
      "«Quédate. Descansa. Aquí abajo no hay que ser valiente.»",
      "Al fondo hay una puerta enorme, medio abierta. Delante, una figura hecha de noche guarda el paso.",
      ["vaelmor", "(una voz que viene de todas partes) Pequeños… Mi heraldo os saluda. Pasad… si podéis."],
    ] },
    c30_tumba: { bg: "cueva", lines: [
      "Dentro de la tumba no hay suelo ni techo: solo una oscuridad inmensa que respira.",
      "En el centro, dos ojos del tamaño de lunas se abren despacio.",
      { sfx: "boss" },
    ] },
    c30_voz: { bg: "viol", lines: [
      ["vaelmor", "Pequeños. Por fin."],
      ["vaelmor", "Mi hermano se muere. Solen. Lo sabéis. Cada deseo que le pedís lo mata un poco más."],
      ["vaelmor", "Dejadme ocupar su sitio. Yo no pediré deseos. No pediré nada. Solo… noche. Y en la noche, nadie volverá a tener miedo de la oscuridad."],
      ["vaelmor", "¿No es eso lo que queríais? ¿Que nadie tuviera miedo?"],
      { if: has("maquina_lista"), then: ["La máquina de Tobble zumba en tu mochila. Está lista. Solo hace falta colocar las reliquias."] },
    ] },
    c30_debil: { bg: "viol", lines: [
      "Vaelmor ruge. La tumba entera tiembla. Sus ojos parpadean, cansados.",
      ["vaelmor", "Sois… fuertes. Más de lo que pensaba. Pero no podéis matarme. Soy la mitad de vuestro sol."],
      ["vaelmor", "Decidid, pequeños. Encerradme, aceptad mi oferta… o intentad despertar a mi hermano moribundo."],
      "Es el final del tercer año. La decisión más importante hasta ahora.",
    ] },

    // ================================================= ARCO 4
    c31_velas: { bg: "patio", lines: [
      { if: () => H(30)() === "sellar", then: ["Vaelmor duerme sellado bajo el Páramo. Pero Solen sigue apagándose: el problema nunca fue solo Vaelmor."] },
      { if: () => H(30)() === "pacto", then: ["Desde el pacto con Vaelmor, la noche dura veinte horas. La gente empieza a olvidar el color del cielo."] },
      { if: () => H(30)() === "solen", then: ["Desde que la luz de los dioses tocó a Solen, a veces se oye una voz en el amanecer, débil, como alguien que habla en sueños."] },
      "Último año en Sunrise Academy. El sol ya no calienta: ilumina, como una lámpara cansada. Los profesores dan clase con velas encendidas a mediodía.",
      "Vuelve a la academia.",
    ] },
    c31_seraphina: { bg: "patio", lines: [
      "Seraphina Lux te busca en el pasillo. Está pálida, con ojeras de no dormir.",
      ["seraphina", "He visto el final del año. Todos estamos en la Cumbre. Tú, yo, Darius, Thorne… todos."],
      ["seraphina", "Y el sol… no sé si el sol está."],
      ["aurelia", "(desde la puerta de su despacho) Venid todos. Es hora de que os cuente lo que deseé hace treinta años."],
      { if: has("aurelia_confiesa"), then: [["aurelia", "Deseé volver. Solo eso. Y el sol pagó mi vuelta con la luz de otro año. Cada día que vivo es un día que le quité."]] },
    ] },
    c32_luces: { bg: "faro", lines: [
      "El espectro del Faro Antiguo ha vuelto a encenderse. Pero esta vez no está solo.",
      "Desde la academia se ven decenas de luces pequeñas flotando alrededor de la torre, como luciérnagas.",
      "Ve al Faro Antiguo.",
    ] },
    c32_ganadores: { bg: "faro", lines: [
      "Las luces se calman. Una a una, toman forma: jóvenes con uniformes de la academia de todas las épocas.",
      ["espectro", "Somos los ganadores. Los que subieron. No estamos muertos. Estamos dentro del sol."],
      ["espectro", "Y el sol… nos está olvidando. Cada año recordamos menos nuestros nombres."],
      ["maelis", "(una luz que se acerca) ¿{n}? Soy yo. Maelis. Del año pasado. ¿Mi pueblo… tiene comida?"],
      { c: [
        { l: "«Sí. Tu deseo se cumplió.»", then: [["maelis", "Entonces valió la pena. Creo. Ya no recuerdo muy bien por qué."]] },
        { l: "«Vamos a sacaros de aquí.»", then: [["maelis", "No sé si eso es posible. Pero gracias por intentarlo."]] },
      ] },
    ] },
    c33_kael: { bg: "patio", lines: [
      { if: () => H(32)() === "contar", then: [["kael", "¿Mi hijo… está ahí? ¿Dentro del sol?"], "Kael se sienta. Es la primera vez que lo ves sin fuerzas para estar de pie."] },
      { if: () => H(32)() === "callar", then: ["No se lo habéis dicho a Kael. Pero él os ve cuchichear, y no es tonto."] },
      ["kael", "Dicen que en la Cueva del Primer Rayo brilla un eco más fuerte que los demás. Uno que pelea."],
      ["kael", "Él entrenaba allí. Voy con vosotros. No me lo discutáis."],
    ] },
    c33_nombre: { bg: "cueva", lines: [
      "El Eco del Campeón baja la espada de luz. Por primera vez, deja de atacar.",
      ["kael", "…Hijo."],
      "El eco mira a Kael. Parpadea. Algo en su cara de luz se parece, por un segundo, a una sonrisa.",
      "«¿Papá? Te… prometí que volvería. Lo siento. Se me olvidó el camino.»",
      ["kael", "No pasa nada. No pasa nada. Ya estoy aquí."],
    ] },
    c34_mascara: { bg: "salon", lines: [
      "El Enmascarado de la Escalera te espera a la salida de clase. Esta vez, se quita la máscara.",
      ["nyx", "Me llamo Nyx. Mi hermana ganó la Cumbre hace tres años. Subí la Escalera para encontrarla."],
      ["nyx", "Quiero entrar en la Cumbre antes de tiempo. Esta noche. Y quiero que me ayudes."],
      ["nyx", "Te espero en el Salón de Baile Hundido. Allí bailábamos de niñas."],
    ] },
    c34_baile: { bg: "salon", lines: [
      "Los fantasmas desaparecen. El salón hundido queda en silencio, con el agua hasta los tobillos y la luz morada reflejada en el techo.",
      ["nyx", "Mi hermana decía que la Cumbre era como este salón: bonita por fuera, llena de fantasmas por dentro."],
      ["nyx", "Si la encuentro, voy a sacarla. Aunque me cueste lo que me cueste."],
      { if: has("hermana_nyx"), then: ["Recuerdas su luz entre los ecos del faro: una chica umbría que tarareaba una canción. Se lo cuentas a Nyx. Ella se tapa la boca con las manos."] },
    ] },
    c35_llamada: { bg: "patio", lines: [
      "Una carta sin sello llega de noche. Dentro, una sola frase con la letra del rey: «Venid a verme. Solos. Sin cortesanos.»",
      "Viaja a la Plaza Real.",
    ] },
    c35_rey: { bg: "salon", lines: [
      "El salón del trono está vacío. El rey Aldric III os recibe sin corona, en bata, con una copa de vino en la mano.",
      ["aldric", "Sé lo que habéis descubierto. Lo del sol. Lo de los deseos."],
      ["aldric", "Cada rey antes que yo lo supo. Los deseos compran paz. Un deseo al año, y Solvaria no tiene guerras, ni hambre, ni plagas."],
      ["aldric", "El sol es el precio. Un precio que pagarán nuestros nietos, no nosotros. Así funciona gobernar."],
      { if: has("darius_aliado"), then: [["darius", "(apareciendo detrás de una columna) Mi padre lo sabía. Por eso quería que ganara. No por gloria. Por un deseo."]] },
      ["lysa", "(desde la puerta, en voz baja) Majestad. Con todo respeto. Eso no es gobernar. Es esconderse."],
    ] },
    c36_prueba: { bg: "patio", lines: [
      "Llega el final del último año. La Prueba de la Cumbre mezcla los cuatro caminos: un combate, un enigma, una decisión y una hazaña.",
      "Esta vez, todo el grupo se ha clasificado. Y esta vez, todos saben lo que hay arriba.",
      ["darius", "{n}. El combate de la Prueba es contra mí. No me lo pongas fácil. Te lo pido de verdad."],
      "Vuelve a la academia para la Prueba.",
    ] },
    c36_ganadores: { bg: "cumbre", lines: [
      "Cuando la última prueba termina, el patio entero se queda en silencio. Luego estalla en aplausos.",
      ["aurelia", "Por primera vez en la historia de Sunrise, la Prueba la gana un grupo entero."],
      "Sobre la colina, la escalera de luz empieza a bajar del cielo.",
      ["aurelia", "Solo uno puede subir. Esa es la regla. Esa ha sido siempre la regla."],
      ["thorne", "Las reglas las hicieron los que querían deseos. Nosotros no queremos deseos."],
    ] },
    c37_mapa: { bg: "faro", lines: [
      ["brisa", "Antes de que nadie suba a ningún sitio, tengo que enseñaros algo."],
      "Brisa despliega sobre la mesa el mapa que trajo de las Islas Perdidas, pintado sobre piel de ballena.",
      ["brisa", "No lleva a un tesoro. Lleva al lugar donde los dioses hicieron a Solen. La Isla del Umbral."],
      ["brisa", "Allí hay una puerta, la Puerta de Aster, que responde a una pregunta sincera. Solo una."],
      "Busca a Varo en Puerto Rayo: es el único que se atreve a navegar hasta las Islas.",
    ] },
    c37_zarpar: { bg: "puerto", lines: [
      ["varo", "¿A las Islas Perdidas? ¿Ahora? ¿Con el sol medio muerto?"],
      ["varo", "…Me encanta. Subid. Pero si morimos, que conste que yo lo dije."],
      "El barco de Varo zarpa entre la niebla. Durante tres días no se ve ni el sol ni las estrellas. Solo bruma.",
      "Al cuarto día, una isla aparece entre la niebla, con una puerta de piedra en la cima.",
    ] },
    c38_hilos: { bg: "lost", lines: [
      "Detrás de la Isla del Umbral, un puente de niebla lleva a otra isla. En ella se oye el ruido de una rueca gigante.",
      "Llega al Telar de Norna.",
    ] },
    c38_norna: { bg: "lost", lines: [
      "Del techo del Telar cuelgan hilos de luz. Millones. Uno por cada vida de Solvaria. Algunos brillan fuerte. Otros están a punto de romperse.",
      ["norna", "Bienvenidos, hilos sueltos. Llevo mucho tiempo mirándoos."],
      ["norna", "Aquí están los vuestros. Mirad: todos llegan hasta la Cumbre del Alba."],
      ["norna", "Y allí, uno de ellos… se convierte en sol."],
      { if: has("fragmento_solen"), then: ["El fragmento de luz de Solen brilla en tu bolsillo, caliente, como un corazón pequeño."] },
    ] },
    c39_escalera: { bg: "cumbre", lines: [
      { if: () => H(36)() === "todos", then: ["Habéis decidido subir todos juntos. La escalera, por primera vez, no dice que no."] },
      { if: () => H(36)() === "uno", then: ["Sube uno. Los demás, en secreto, detrás. La escalera tiembla, como si notara el peso de más."] },
      "La escalera de luz se abre sobre Sunrise Academy. Toda la academia mira hacia arriba.",
      ["aurelia", "Voy con vosotros. Esta vez sé lo que hay arriba. Esta vez no voy a pedir nada."],
      "Sube a la Cumbre del Alba.",
    ] },
    c39_deseos: { bg: "cumbre", lines: [
      "Cada peldaño es un ganador. Cada uno susurra su deseo al pasar.",
      "«Que mi madre se cure.» «Que no haya guerra.» «Que mi pueblo tenga comida.» «Volver.»",
      "Arriba, bloqueando el paso, espera el Guardián de la Cumbre: una figura enorme hecha de 97 deseos.",
      "Detrás de él, algo respira muy despacio. Algo dorado. Algo muy cansado.",
    ] },
    c40_solen: { bg: "cumbre", lines: [
      "En la Cumbre del Alba no hay nada más que luz. Y en el centro de la luz, Solen.",
      "Un anciano de oro, sentado en el suelo, que apenas puede abrir los ojos.",
      ["solen", "Hola, pequeños. Os he visto subir. Todos estos años, os he visto subir."],
      ["solen", "Cada deseo lo pagué yo. Con gusto, al principio. Me gustaba ver felices a los que subían."],
      ["solen", "Ya no me queda casi nada. Decidid qué hacer conmigo. Yo ya no puedo."],
      "Los 97 deseos se levantan a tu alrededor. No quieren desaparecer. Se juntan en una sola forma.",
    ] },
    c40_decision: { bg: "cumbre", lines: [
      "El eco de todos los deseos se deshace en una lluvia de luz. Los ganadores de todos los años flotan a vuestro alrededor, esperando.",
      ["solen", "Ya está. Ahora os toca a vosotros."],
      ["aurelia", "Pase lo que pase, estoy orgullosa. De todos."],
      ["thorne", "Manada. Hasta el final."],
      "Es el momento. El grupo decide qué hacer con el sol.",
    ] },
  });
})();
